/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-07-26 04:53:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"utf-8\">\r\n");
      out.write("		<title>Login</title>\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"css/body.css\">\r\n");
      out.write("		<style>\r\n");
      out.write("			#container{\r\n");
      out.write("               width:300px;\r\n");
      out.write("               border:5px solid navy;\r\n");
      out.write("               padding:30px;\r\n");
      out.write("               margin:0 auto;\r\n");
      out.write("               margin-top:50px;\r\n");
      out.write("            }\r\n");
      out.write("            #logo{\r\n");
      out.write("            	margin: 0 auto;\r\n");
      out.write("                width: 150px;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("            }\r\n");
      out.write("            input{\r\n");
      out.write("                border: 1px solid #ccc;\r\n");
      out.write("                width: 289px;\r\n");
      out.write("                height: 25px;\r\n");
      out.write("                font-size: 16px;\r\n");
      out.write("                padding: 5px;\r\n");
      out.write("                margin-bottom: 10px;\r\n");
      out.write("                color:#7B2B63;\r\n");
      out.write("            }\r\n");
      out.write("            .idpw{\r\n");
      out.write("            	border-color:navy;\r\n");
      out.write("            	color:#7B2B63;;\r\n");
      out.write("            	border-radius: 4px;\r\n");
      out.write("            }\r\n");
      out.write("            h1,h2{\r\n");
      out.write("                color:navy;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("            }\r\n");
      out.write("            .loginButton{\r\n");
      out.write("                width:255px;\r\n");
      out.write("                height: 49px;\r\n");
      out.write("                font-weight: bold;\r\n");
      out.write("                font-size: 20px;\r\n");
      out.write("                background-color: navy;\r\n");
      out.write("                color: #fff;\r\n");
      out.write("                border: none;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("                border-radius:15px;\r\n");
      out.write("            }\r\n");
      out.write("            .loginButton:hover{\r\n");
      out.write("            	background-color:#7B2B63;\r\n");
      out.write("            }\r\n");
      out.write("            .div_btn{\r\n");
      out.write("            	padding:20px;\r\n");
      out.write("            	margin:0 auto;\r\n");
      out.write("            }\r\n");
      out.write("            a{\r\n");
      out.write("                text-decoration-line: none;\r\n");
      out.write("            	font-size: 16px;\r\n");
      out.write("            }\r\n");
      out.write("            a:hover{\r\n");
      out.write("            	font-weight:bold;\r\n");
      out.write("            }\r\n");
      out.write("            .div_a{\r\n");
      out.write("            	margin:0 auto;\r\n");
      out.write("            	width:255px;\r\n");
      out.write("            	text-align:center;\r\n");
      out.write("            	padding: 15px;\r\n");
      out.write("            }\r\n");
      out.write("		</style>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("		<div id=\"container\">\r\n");
      out.write("			<div id=\"logo\"><a href=\"https://www.fmglobal.com/\"><img src=\"image/fmLogo.svg\" alt=\"logo\"></a></div>\r\n");
      out.write("			<div><h1>Proposal System</h1></div>\r\n");
      out.write("				<form method=\"post\" action=\"loginprogress.jsp\">\r\n");
      out.write("					<div>\r\n");
      out.write("						<input class=\"idpw\" type=\"email\" name=\"userEmail\" required placeholder=\"email\">\r\n");
      out.write("					</div>\r\n");
      out.write("					 <div>\r\n");
      out.write("					     <input class=\"idpw\" type=\"password\" name=\"userPassword\" required placeholder=\"password\">\r\n");
      out.write("					 </div>\r\n");
      out.write("					<div class=\"div_btn\">\r\n");
      out.write("						<input type=\"submit\" class=\"loginButton\" id=\"submit\" value=\"Login\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			<div class=\"div_a\"><a href = \"findPassword.jsp\">Need help? CONTACT US!</a></div>\r\n");
      out.write("			<div class=\"div_a\"><a href = \"account.jsp\">CREATE ACCOUNT</a></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
